# Generated by Django 4.2.1 on 2023-07-07 16:10

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/images', validators=[users.models.validate_image], verbose_name='Profile image'),
        ),
    ]
