# Generated by Django 4.2.3 on 2023-07-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_article_author',
        ),
    ]
